name: Create Tag on Changed Modules

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Publish
        if: (github.event.pull_request.merged == true || (github.ref == 'refs/heads/main' && github.event_name == 'push'))
        run: |
          tag_name="v0.0.$GITHUB_RUN_NUMBER"
          git tag -a $tag_name -m "${{ github.event.head_commit.message }}"
          git push origin $tag_name

      - name: Generate Docs
        uses: ktr0731/godoc-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
